### ISSUE TITLE
Open PSD or high DPI files

### ISSUE THREAD

**Issue by leonardolb** [patrickgalbraith/zombicide-card-database#13]
Hi! can you post newest psd file so we can keep editing and adding content or post again all cards from all editions?

In your blog there is only zombie cards till 145 (actual number is 245).

thanks!

**Comment by patrickgalbraith** [comment]
Hi @leonardolb these files were originally extracted from the Zombicide mobile app.

The program I used to extract the assets is (https://github.com/ata4/disunity) since it is a Unity3d app. First you need to find the Zombicide OBB file on your Android Phones SDK. Extract that using 7-zip or similar and then find /assets/bin/Data and extract the files in there using disunity.

You will need to convert the raw image files into PSD's using a script, I wrote about how I did this on my blog.
